import { jsPDF } from "jspdf";
import { computeTotals, formatCurrency, type PayslipData } from "./payslip-types";

export function downloadPayslipPDF(data: PayslipData) {
  const totals = computeTotals(data);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = 0;

  // Header band
  doc.setFillColor(34, 28, 58);
  doc.rect(0, 0, W, 110, "F");

  if (data.companyLogo) {
    try {
      doc.addImage(data.companyLogo, "PNG", M, 30, 50, 50);
    } catch {
      /* ignore unsupported image */
    }
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("PAYSLIP", M + 64, 50);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(data.companyName || "Company Name", M + 64, 70);

  const period = data.payPeriod
    ? new Date(data.payPeriod + "-02").toLocaleDateString("en-US", { month: "long", year: "numeric" })
    : "—";
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("PAY PERIOD", W - M, 50, { align: "right" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(period, W - M, 70, { align: "right" });

  // Employee
  y = 150;
  doc.setTextColor(120, 120, 130);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  ["EMPLOYEE", "EMPLOYEE ID", "POSITION"].forEach((label, i) => {
    doc.text(label, M + i * 165, y);
  });
  doc.setTextColor(20, 20, 30);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  [data.employeeName || "—", data.employeeId || "—", data.role || "—"].forEach((v, i) => {
    doc.text(v, M + i * 165, y + 18, { maxWidth: 155 });
  });

  // Divider
  y = 200;
  doc.setDrawColor(230, 230, 235);
  doc.line(M, y, W - M, y);

  // Lines
  y += 30;
  doc.setTextColor(120, 120, 130);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("DESCRIPTION", M, y);
  doc.text("AMOUNT", W - M, y, { align: "right" });

  const lines: { label: string; value: number; ded?: boolean }[] = [
    { label: "Basic Salary", value: data.basic },
    { label: "Allowances", value: data.allowances },
    { label: "Tax", value: totals.tax, ded: true },
    { label: "Other Deductions", value: data.deductions, ded: true },
  ];

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  lines.forEach((l) => {
    y += 24;
    doc.setTextColor(50, 50, 60);
    doc.text(l.label, M, y);
    if (l.ded) doc.setTextColor(220, 60, 80);
    else doc.setTextColor(20, 20, 30);
    doc.text(`${l.ded ? "-" : ""}${formatCurrency(l.value)}`, W - M, y, { align: "right" });
  });

  // Totals
  y += 30;
  doc.setDrawColor(230, 230, 235);
  doc.line(M, y, W - M, y);

  y += 22;
  doc.setTextColor(80, 80, 90);
  doc.setFontSize(11);
  doc.text("Gross Salary", M, y);
  doc.setTextColor(20, 20, 30);
  doc.text(formatCurrency(totals.gross), W - M, y, { align: "right" });

  y += 20;
  doc.setTextColor(120, 120, 130);
  doc.text("Total Deductions", M, y);
  doc.text(`-${formatCurrency(totals.totalDeductions)}`, W - M, y, { align: "right" });

  // Net pay band
  y += 30;
  doc.setFillColor(120, 70, 220);
  doc.roundedRect(M, y, W - 2 * M, 70, 10, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("NET PAY", M + 20, y + 28);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(formatCurrency(totals.net), W - M - 20, y + 42, { align: "right" });

  // Footer
  doc.setTextColor(160, 160, 170);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("This is a computer-generated payslip.", M, doc.internal.pageSize.getHeight() - 30);
  doc.text("Generated by Payslip.io", W - M, doc.internal.pageSize.getHeight() - 30, { align: "right" });

  const safeName = (data.employeeName || "payslip").replace(/[^\w-]+/g, "_");
  doc.save(`Payslip_${safeName}_${data.payPeriod || "draft"}.pdf`);
}
